### ISSUE TITLE
Help for Vernissage SDK

### ISSUE THREAD

**Issue by LadderOperator** [t-b/matrixfilereader#3]
😞 I have been Googling the Vernissage SDK for several days, only to find this repository. 

I have an old manual of Vernissage which says the SDK Package should be downloaded from [the old Omicron site](http://www.omicron.de/en/software-downloads), but it seems that the old Omicron website has been abandon. And, the new Scienta Omicron website doesn't offer download links any more...

I need the SDK to develope. Do you know where to download the Vernisssage SDK?

:smile: Many thanks and best regards

**Comment by t-b** [comment]
You need to contact Scienta Omicron support. Only they can provide it.

What do you want to do with it? (I'm just curious).
